font:
  normal:
    family: Sauce Code Pro Nerd Font

selection:
  save_to_clipboard: true

# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    background: '0x282828'
    foreground: '0xebdbb2'

  # Normal colors
  normal:
    black:   '0x282828'
    red:     '0xcc241d'
    green:   '0x8ae234'
    yellow:  '0xd79921'
    blue:    '0x729fcf'
    magenta: '0xb16286'
    cyan:    '0x689d6a'
    white:   '0xa89984'

  # Bright colors
  bright:
    black:   '0x928374'
    red:     '0xfb4934'
    green:   '0x8ae234'
    yellow:  '0xfabd2f'
    blue:    '0x729fcf'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xebdbb2'

# Regex hints
hints:
  alphabet: "caeitrnsouglhdwm"
  enabled:
   - regex: "(ipfs:|ipns:|mailto:|https:|http:|file:|git:|ssh:|ftp:)\
             [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
     command: xdg-open
     post_processing: true
     mouse:
       enabled: true
       mods: None
     binding:
       key: S
       mods: Control

# The following key bindings are adapted for a modified VOU layout
# and mostly won't make sense on a normal QWERTY/QWERTZ layout
key_bindings:
  - { key: L,         mods: Control,                    action: ClearLogNotice }
  - { key: L,         mods: Control, mode: ~Vi|~Search, chars: "\x0c"          }
  - { key: PageUp,                   mode: ~Alt,        action: ScrollHalfPageUp,  }
  - { key: PageDown,                 mode: ~Alt,        action: ScrollHalfPageDown }
  - { key: Home,      mods: Shift,   mode: ~Alt,        action: ScrollToTop,   }
  - { key: End,       mods: Shift,   mode: ~Alt,        action: ScrollToBottom }

  # Vi Mode
  - { key: N,      mods: Control,       mode: ~Search,    action: ToggleViMode            }
  - { key: N,      mods: Control,       mode: Vi|~Search, action: ScrollToBottom          }
  - { key: Escape,                      mode: Vi|~Search, action: ToggleViMode            }
  - { key: Escape,                      mode: Vi|~Search, action: ScrollToBottom          }
  - { key: Escape,                      mode: Vi|~Search, action: ClearSelection          }
  - { key: R,                           mode: Vi|~Search, action: ToggleViMode            }
  - { key: R,                           mode: Vi|~Search, action: ScrollToBottom          }
  - { key: C,      mods: Control,       mode: Vi|~Search, action: ToggleViMode            }
  - { key: O,                           mode: Vi|~Search, action: ScrollLineUp            }
  - { key: E,                           mode: Vi|~Search, action: ScrollLineDown          }
  - { key: G,                           mode: Vi|~Search, action: ScrollToTop             }
  - { key: G,      mods: Shift,         mode: Vi|~Search, action: ScrollToBottom          }
  - { key: O,      mods: Shift,         mode: Vi|~Search, action: ScrollHalfPageUp        }
  - { key: E,      mods: Shift,         mode: Vi|~Search, action: ScrollHalfPageDown      }
  - { key: Y,                           mode: Vi|~Search, action: Copy                    }
  - { key: Y,                           mode: Vi|~Search, action: ClearSelection          }
  - { key: Copy,                        mode: Vi|~Search, action: ClearSelection          }
  - { key: V,                           mode: Vi|~Search, action: ToggleBlockSelection    }
  - { key: V,      mods: Shift,         mode: Vi|~Search, action: ToggleLineSelection     }
  - { key: V,      mods: Alt,           mode: Vi|~Search, action: ToggleSemanticSelection }
  - { key: Return,                      mode: Vi|~Search, action: Open                    }
  - { key: O,      mods: Control,       mode: Vi|~Search, action: Up                      }
  - { key: E,      mods: Control,       mode: Vi|~Search, action: Down                    }
  - { key: A,                           mode: Vi|~Search, action: Left                    }
  - { key: I,                           mode: Vi|~Search, action: Right                   }
  - { key: Up,                          mode: Vi|~Search, action: Up                      }
  - { key: Down,                        mode: Vi|~Search, action: Down                    }
  - { key: Left,                        mode: Vi|~Search, action: Left                    }
  - { key: Right,                       mode: Vi|~Search, action: Right                   }
  - { key: Key0,                        mode: Vi|~Search, action: First                   }
  - { key: Key4,                        mode: Vi|~Search, action: Last                    }
  - { key: Key6,                        mode: Vi|~Search, action: FirstOccupied           }
  - { key: H,      mods: Shift,         mode: Vi|~Search, action: High                    }
  - { key: M,      mods: Shift,         mode: Vi|~Search, action: Middle                  }
  - { key: L,      mods: Shift,         mode: Vi|~Search, action: Low                     }
  - { key: A,      mods: Control,       mode: Vi|~Search, action: SemanticLeft            }
  - { key: I,      mods: Control,       mode: Vi|~Search, action: SemanticRight           }
  - { key: U,      mods: Control,       mode: Vi|~Search, action: SemanticRightEnd        }
  - { key: A,      mods: Shift,         mode: Vi|~Search, action: WordLeft                }
  - { key: I,      mods: Shift,         mode: Vi|~Search, action: WordRight               }
  - { key: U,      mods: Shift,         mode: Vi|~Search, action: WordRightEnd            }
  - { key: Key5,                        mode: Vi|~Search, action: Bracket                 }
  - { key: J,                           mode: Vi|~Search, action: SearchForward           }
  - { key: J,      mods: Shift,         mode: Vi|~Search, action: SearchBackward          }
  - { key: N,                           mode: Vi|~Search, action: SearchNext              }
  - { key: N,      mods: Shift,         mode: Vi|~Search, action: SearchPrevious          }
