theme = "gruvbox"

[editor]
color-modes = true
cursorline = true
idle-timeout = 0
end-of-line-diagnostics = "hint"

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.statusline]
left = ["mode", "spacer", "spinner", "file-name", "file-modification-indicator", "read-only-indicator"]
center = ["selections"]
right = ["diagnostics", "spacer", "position", "spacer", "position-percentage", "spacer", "file-encoding"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.soft-wrap]
enable = true

[keys.normal]
# Movement
o = "move_visual_line_up"
e = "move_visual_line_down"
a = "move_char_left"
i = "move_char_right"
O = "half_page_up"
E = "half_page_down"
A = "move_prev_word_start"
I = "move_next_word_start"
G = "goto_last_line"

# Joining, replacing and redoing
"ö" = "join_selections"
"ü" = "replace"
"Ü" = "replace_with_yanked"
"ä" = "redo"

# Switching to insert mode
r = "insert_mode"
R = "append_mode"
w = "insert_at_line_end"
W = "insert_at_line_start"
l = "open_below"
L = "open_above"

# Yanking and searching
Y = ":clipboard-yank"
j = "search"
J = ["search_selection", "global_search"]
h = ["search_selection", "search_next"]
H = ["select_all", "select_regex"]

# Mimic vim like line mode
V = ["extend_line_below", "select_mode"]
X = ["extend_line_up", "extend_to_line_bounds"]

# Other
b = "buffer_picker"
B = "goto_last_accessed_file"
k = "hover"
q = ":quit"
_ = "command_mode"

[keys.normal.t]
# Going to arbitrary positions
n = "goto_definition"
N = "goto_declaration"
r = "goto_reference"
s = "symbol_picker"
S = "workspace_symbol_picker"
t = "goto_type_definition"
w = "goto_word"
h = "command_palette"

# Traversing jumplist
k = "jumplist_picker"
i = "jump_forward"
o = "jump_backward"

# Going to next (unimpaired like mappings)
a = "goto_next_parameter"
e = "goto_next_diag"
c = "goto_next_comment"
f = "goto_next_function"
l = "goto_next_class"
m = "goto_next_change"
M = "goto_last_change"
p = "goto_next_paragraph"
T = "goto_next_test"
space = "add_newline_below"

[keys.normal.f]
# Going to previous (unimpaired like mappings)
a = "goto_prev_parameter"
e = "goto_prev_diag"
c = "goto_prev_comment"
f = "goto_prev_function"
l = "goto_prev_class"
m = "goto_prev_change"
M = "goto_first_change"
T = "goto_prev_test"
p = "goto_prev_paragraph"
space = "add_newline_above"

[keys.normal.space]
b = ":buffer-close"
e = "extend_to_line_end"
l = "last_picker"
s = ":update"
q = "replay_macro"
"'" = "no_op"

[keys.select]
# Movement
o = "extend_visual_line_up"
e = "extend_visual_line_down"
a = "extend_char_left"
i = "extend_char_right"
O = "half_page_up"
E = "half_page_down"
A = "extend_prev_word_start"
I = "extend_next_word_start"
G = "goto_last_line"
X = ["extend_line_up", "extend_to_line_bounds"]

# Switching to insert mode
r = "insert_mode"
R = "append_mode"
w = "insert_at_line_end"
W = "insert_at_line_start"

# Flipping the selection cursor and anchor
l = "flip_selections"
L = "flip_selections"

# Yanking and searching
Y = ":clipboard-yank"
j = "search"
J = ["search_selection", "global_search"]
h = ["search_selection", "search_next"]
H = ["select_all", "select_regex"]

# Other
b = "buffer_picker"
B = "goto_last_accessed_file"
k = "hover"
q = ":quit"
_ = "command_mode"

[keys.insert]
C-backspace = "delete_word_backward"
