[[language]]
name = "c"
auto-format = true
language-servers = ["clangd", "typos"]

[[language]]
name = "cpp"
auto-format = true
language-servers = ["clangd", "typos"]

[[language]]
name = "git-commit"
language-servers = ["harper"]

[[language]]
name = "markdown"
language-servers = ["mdpls", "harper"]

[[language]]
name = "python"
auto-format = true
language-servers = ["ruff", "pylsp", "typos"]

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "typos"]

[[language]]
name = "typst"
auto-format = true
language-servers = ["tinymist", "harper"]


[language-server.harper]
command = "harper-ls"
args = ["--stdio"]
config = { harper-ls.linters.SentenceCapitalizatoin = false }

[language-server.mdpls]
command = "mdpls"

[language-server.rust-analyzer]
config = { check.command = "clippy" }

[language-server.tinymist]
config = { formatterMode = "typstyle" }

[language-server.typos]
command = "typos-lsp"
