[ids]
*
-feed

[global]
chord_timeout = 25

[aliases]
\ = enter
enter = enter

[main]
# upper row
1 = esc
2 = v
3 = .
4 = o
5 = u
6 = '
7 = q
8 = g
9 = l
0 = h
- = f
= = ?

# home row
tab = backspace
q = c
w = a
e = e
r = i
t = [
u = b
i = t
o = r
p = n
[ = s
] = j

# lower row
capslock = overload(alt, -)
a = y
s = x
d = ,
f = z
g = ;
j = p
k = d
l = w
; = m
' = k
enter = /

# thumb keys
c = overload(control, tab)
v = layer(shift)
b = layer(movement)
n = layer(symbol)
m = space
, = overload(meta, enter)

# combos home row
e+r = *
i+o = (
w+e = |
o+p = )
w+r = @
i+p = &
q+r = <
i+[ = }
q+e = >
o+[ = \
q+w = $
p+[ = !

# combos upper row
4+5 = G-7
8+9 = G-0
3+4 = 102nd
9+0 = S-102nd
3+5 = ^
8+0 = G--
2+5 = G-q
8+- = G-102nd
2+4 = ]
9+- = %
2+3 = +
0+- = G-]

# combos lower row
d+f = G-8
k+l = G-9
s+f = 0
k+; = 1
s+d = 2
l+; = 3
a+f = 4
k+' = 5
a+d = 6
l+' = 7
a+s = 8
;+' = 9

# disable unused keys
esc = noop
` = noop
backspace = noop
y = noop
h = noop
shift = noop
z = noop
x = noop
. = noop
/ = noop
up = noop
down = noop
left = noop
right = noop
control = noop
meta = noop
alt = noop
space = noop
altgr = noop
102nd = noop

[movement]
# upper row
1 = layer(control-meta)
2 = layer(control-alt)
3 = backspace
4 = up
5 = delete
6 = A-f4
7 = }
8 = 7
9 = 8
0 = 9
- = >

# home row
tab = layer(control-shift)
q = layer(shift)
w = left
e = down
r = right
t = pageup
u = ]
i = 4
o = 5
p = 6
[ = .
] = backspace

# lower row
capslock = layer(meta)
a = layer(control)
s = insert
d = home
f = end
g = pagedown
j = &
k = 1
l = 2
; = 3
' = ,

# thumb keys
, = 0

[symbol]
# upper row
1 = ~
2 = ]
3 = 102nd
4 = |
5 = G-7
6 = `
7 = G--
8 = G-0
9 = ^
0 = S-102nd
- = /
= = #

# home row
tab = .
q = >
w = <
e = @
r = *
t = !
u = G-]
i = (
o = )
p = &
[ = }
] = +

# lower row
capslock = G-m
a = 0
s = G-q
d = $
f = G-8
g = _
j = G-102nd
k = G-9
l = \
; = %
' = 1
enter = G-e

# thumb keys
c = S-tab
v = space

[movement+symbol]
# upper row
1 = f1
2 = f2
3 = f3
4 = f4
5 = f5
6 = f6
7 = f7
8 = f8
9 = f9
0 = f10
- = f11
= = f12

# home row
q = pause
w = previoussong
e = play
r = nextsong
t = brightnessup
u = M-f1
i = M-f2
o = M-f3
p = M-f4
[ = M-f5
] = M-f6

# lower row
a = print
s = mute
d = volumedown
f = volumeup
g = brightnessdown
j = M-f7
k = M-f8
l = M-f9
; = M-f10
' = M-f11
enter = M-f12

[shift]
tab = C-backspace

[control-meta:C-M]

[control-alt:C-A]

[control-shift:C-S]
